title: Crime Prediction in Chicago
logo: assets/img/final-logo.png
description: Geospatial Data Science in Python.
show_downloads: false
repository: shevilovia/Crime-Prediction-In-Chicago
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
